import { NonEmptyArray } from 'type-graphql/dist/interfaces/NonEmptyArray';

import {
  CreateOneAccountResolver,
  UpdateOneAccountResolver,
  DeleteOneAccountResolver,
  UpsertOneAccountResolver,
  FindManyTypeformApplicationResolver,
  CreateOneTypeformApplicationResolver,
  UpdateOneTypeformApplicationResolver,
  DeleteOneTypeformApplicationResolver,
  CreateOneEventResolver,
  UpdateOneEventResolver,
  DeleteOneEventResolver,
  UpsertOneEventResolver,
  FindManyEventResolver,
  CreateOneProfileResolver,
  UpdateOneProfileResolver,
  // DeleteProfileResolver,
  UpsertOneProfileResolver,
  FindManyProfileResolver,
  FindUniqueProfileResolver,
  CreateOneEventReservationResolver,
  UpdateOneEventReservationResolver,
  DeleteOneEventReservationResolver,
  UpsertOneEventReservationResolver,
  FindManyEventReservationResolver,
} from '@generated/type-graphql';

export const exposedResolvers: NonEmptyArray<Function> = [
  CreateOneAccountResolver,
  UpdateOneAccountResolver,
  DeleteOneAccountResolver,
  UpsertOneAccountResolver,
  FindManyTypeformApplicationResolver,
  CreateOneTypeformApplicationResolver,
  UpdateOneTypeformApplicationResolver,
  DeleteOneTypeformApplicationResolver,
  CreateOneEventResolver,
  UpdateOneEventResolver,
  DeleteOneEventResolver,
  UpsertOneEventResolver,
  FindManyEventResolver,
  CreateOneProfileResolver,
  UpdateOneProfileResolver,
  // DeleteProfileResolver,
  UpsertOneProfileResolver,
  FindManyProfileResolver,
  FindUniqueProfileResolver,
  CreateOneEventReservationResolver,
  UpdateOneEventReservationResolver,
  DeleteOneEventReservationResolver,
  UpsertOneEventReservationResolver,
  FindManyEventReservationResolver,
];
