/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  title: 'ACM Portal',
  tagline: 'Learn more about the ACM Portal, microservices, and core infrastructure',
  url: 'https://docs.portal.acmutd.co',
  baseUrl: '/',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',
  organizationName: 'ACM',
  projectName: 'portal-next',
  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath:
            'C:\\UTD\\Senior Year\\Fall Semester 2022\\ACM Development\\portal-next\\apps\\documentation\\sidebars.js',
          editUrl:
            'https://github.com/acmutstartd/docs-leadership/tree/main/packages/create-docusaurus/templates/shared/',
        },
        blog: {
          showReadingTime: true,
          editUrl:
            'https://github.com/acmutd/docs-leadership/tree/main/packages/create-docusaurus/templates/shared/',
        },
        theme: {
          customCss:
            'C:\\UTD\\Senior Year\\Fall Semester 2022\\ACM Development\\portal-next\\apps\\documentation\\src\\css\\custom.css',
        },
      },
    ],
  ],
  themeConfig: {
    navbar: {
      title: 'Portal',
      logo: {
        alt: 'Logo',
        src: 'img/logo-black.svg',
        srcDark: 'img/logo-white.svg',
      },
      items: [
        {
          type: 'doc',
          docId: 'intro',
          position: 'left',
          label: 'Docs',
        },
        {
          to: '/blog',
          label: 'Blog',
          position: 'left',
        },
        {
          href: 'https://github.com/acmutd/portal-next',
          label: 'GitHub',
          position: 'right',
        },
      ],
      hideOnScroll: false,
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Portal',
          items: [
            {
              label: 'Docs',
              to: '/docs/intro',
            },
            {
              label: 'Blog',
              to: '/blog',
            },
          ],
        },
        {
          title: 'Social',
          items: [
            {
              label: 'LinkedIn',
              href: 'https://www.linkedin.com/company/27182339',
            },
            {
              label: 'Twitter',
              href: 'https://twitter.com/acmutd',
            },
            {
              label: 'Instagram',
              href: 'https://instagram.com/acmutd',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/acmutd',
            },
            {
              label: 'Discord',
              href: 'https://acmutd.co/discord',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'Leadership Site',
              href: 'https://leadership.acmutd.co',
            },
            {
              label: 'ACM Website',
              href: 'https://acmutd.co',
            },
            {
              label: 'ACM Portal',
              href: 'https://portal.acmutd.co',
            },
          ],
        },
      ],
      copyright: 'Copyright © 2022 ACM Portal. Built with Docusaurus.',
    },
    prism: {
      theme: {
        plain: {
          color: '#393A34',
          backgroundColor: '#f6f8fa',
        },
        styles: [
          {
            types: ['comment', 'prolog', 'doctype', 'cdata'],
            style: {
              color: '#999988',
              fontStyle: 'italic',
            },
          },
          {
            types: ['namespace'],
            style: {
              opacity: 0.7,
            },
          },
          {
            types: ['string', 'attr-value'],
            style: {
              color: '#e3116c',
            },
          },
          {
            types: ['punctuation', 'operator'],
            style: {
              color: '#393A34',
            },
          },
          {
            types: [
              'entity',
              'url',
              'symbol',
              'number',
              'boolean',
              'variable',
              'constant',
              'property',
              'regex',
              'inserted',
            ],
            style: {
              color: '#36acaa',
            },
          },
          {
            types: ['atrule', 'keyword', 'attr-name', 'selector'],
            style: {
              color: '#00a4db',
            },
          },
          {
            types: ['function', 'deleted', 'tag'],
            style: {
              color: '#d73a49',
            },
          },
          {
            types: ['function-variable'],
            style: {
              color: '#6f42c1',
            },
          },
          {
            types: ['tag', 'selector', 'keyword'],
            style: {
              color: '#00009f',
            },
          },
        ],
      },
      darkTheme: {
        plain: {
          color: '#F8F8F2',
          backgroundColor: '#282A36',
        },
        styles: [
          {
            types: ['prolog', 'constant', 'builtin'],
            style: {
              color: 'rgb(189, 147, 249)',
            },
          },
          {
            types: ['inserted', 'function'],
            style: {
              color: 'rgb(80, 250, 123)',
            },
          },
          {
            types: ['deleted'],
            style: {
              color: 'rgb(255, 85, 85)',
            },
          },
          {
            types: ['changed'],
            style: {
              color: 'rgb(255, 184, 108)',
            },
          },
          {
            types: ['punctuation', 'symbol'],
            style: {
              color: 'rgb(248, 248, 242)',
            },
          },
          {
            types: ['string', 'char', 'tag', 'selector'],
            style: {
              color: 'rgb(255, 121, 198)',
            },
          },
          {
            types: ['keyword', 'variable'],
            style: {
              color: 'rgb(189, 147, 249)',
              fontStyle: 'italic',
            },
          },
          {
            types: ['comment'],
            style: {
              color: 'rgb(98, 114, 164)',
            },
          },
          {
            types: ['attr-name'],
            style: {
              color: 'rgb(241, 250, 140)',
            },
          },
        ],
      },
      additionalLanguages: [],
      magicComments: [
        {
          className: 'theme-code-block-highlighted-line',
          line: 'highlight-next-line',
          block: {
            start: 'highlight-start',
            end: 'highlight-end',
          },
        },
      ],
    },
    colorMode: {
      defaultMode: 'light',
      disableSwitch: false,
      respectPrefersColorScheme: true,
    },
    docs: {
      versionPersistence: 'localStorage',
      sidebar: {
        hideable: false,
        autoCollapseCategories: false,
      },
    },
    metadata: [],
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 3,
    },
  },
  baseUrlIssueBanner: true,
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
    localeConfigs: {},
  },
  onDuplicateRoutes: 'warn',
  staticDirectories: ['static'],
  customFields: {},
  plugins: [],
  themes: [],
  scripts: [],
  stylesheets: [],
  clientModules: [],
  titleDelimiter: '|',
  noIndex: false,
};
