import { NonEmptyArray } from 'type-graphql/dist/interfaces/NonEmptyArray';

import {
  CreateOneAccountResolver,
  UpdateOneAccountResolver,
  DeleteOneAccountResolver,
  UpsertOneAccountResolver,
  FindManyTypeformApplicationResolver,
  FindFirstTypeformApplicationResolver,
  CreateOneTypeformApplicationResolver,
  UpdateOneTypeformApplicationResolver,
  DeleteOneTypeformApplicationResolver,
  CreateOneEventResolver,
  UpdateOneEventResolver,
  DeleteOneEventResolver,
  UpsertOneEventResolver,
  FindManyEventResolver,
  CreateOneProfileResolver,
  UpdateOneProfileResolver,
  // DeleteProfileResolver,
  UpsertOneProfileResolver,
  FindManyProfileResolver,
  FindUniqueProfileResolver,
  CreateOneEventReservationResolver,
  UpdateOneEventReservationResolver,
  DeleteOneEventReservationResolver,
  UpsertOneEventReservationResolver,
  FindManyEventReservationResolver,
  CreateOneVanityLinkResolver,
  UpdateOneVanityLinkResolver,
  DeleteOneVanityLinkResolver,
  FindManyVanityLinkResolver,
  UserRelationsResolver,
  FindManyApplicationResolver, 
  FindManyFilledApplicationResolver,
  ApplicationRelationsResolver,
  FilledApplicationRelationsResolver,
  CreateOneFilledApplicationResolver,
  FindUniqueApplicationResolver,
  ProfileRelationsResolver,
  UpdateOneFilledApplicationResolver,
} from '@generated/type-graphql';

export const exposedResolvers: NonEmptyArray<Function> = [
  UserRelationsResolver,
  CreateOneAccountResolver,
  UpdateOneAccountResolver,
  DeleteOneAccountResolver,
  UpsertOneAccountResolver,
  FindManyTypeformApplicationResolver,
  FindFirstTypeformApplicationResolver,
  CreateOneTypeformApplicationResolver,
  UpdateOneTypeformApplicationResolver,
  DeleteOneTypeformApplicationResolver,
  FindManyApplicationResolver,
  CreateOneEventResolver,
  UpdateOneEventResolver,
  DeleteOneEventResolver,
  UpsertOneEventResolver,
  FindManyEventResolver,
  CreateOneProfileResolver,
  UpdateOneProfileResolver,
  // DeleteProfileResolver,
  UpsertOneProfileResolver,
  FindManyProfileResolver,
  FindUniqueProfileResolver,
  CreateOneEventReservationResolver,
  UpdateOneEventReservationResolver,
  DeleteOneEventReservationResolver,
  UpsertOneEventReservationResolver,
  FindManyEventReservationResolver,
  CreateOneVanityLinkResolver,
  UpdateOneVanityLinkResolver,
  DeleteOneVanityLinkResolver,
  FindManyVanityLinkResolver,
  FindManyFilledApplicationResolver,
  CreateOneFilledApplicationResolver,
  FindUniqueApplicationResolver,
  ApplicationRelationsResolver,
  FilledApplicationRelationsResolver,
  ProfileRelationsResolver,
  UpdateOneFilledApplicationResolver,
];  
