query getDirectorManagementPageInfo {
  directors {
    id
    divisions {
      deptName
    }
    officer {
      profile {
        firstName
        lastName
      }
    }
  }
}

mutation deleteDirector($where: DirectorWhereUniqueInput!) {
  deleteOneDirector(where: $where) {
    id
  }
}

query getAddDirectorPageInfo {
  officers {
    id
    profile {
      firstName
      lastName
    }
  }
  divisions {
    id
    deptName
  }
}

mutation addNewDirector($where: DirectorWhereUniqueInput!, $create: DirectorCreateInput!, $update: DirectorUpdateInput!) {
  upsertOneDirector(where: $where, create: $create, update: $update) {
    id
  }
}
