query getAddOfficerPageData {
  me {
    profile {
      officer {
        divisions {
          id
          deptName
        }
      }
    }
  }
  officerEligibleProfiles {
    lastName
    firstName
    netid
    id
  }
}

mutation addUserToDivision($data: OfficerUpdateInput!, $where: OfficerWhereUniqueInput!) {
  updateOneOfficer(data: $data, where: $where) {
    profile {
      firstName
      lastName
      officer {
        divisionIds
        divisions {
          deptName
        }
      }
    }
  }
}

mutation createOneOfficer($data: OfficerCreateInput!) {
  createOneOfficer(data: $data) {
    id
    profile {
      id
      firstName
      lastName
    }
    divisions {
      id
      deptName
    }
  }
}