import { NonEmptyArray } from 'type-graphql/dist/interfaces/NonEmptyArray';

import {
  CreateAccountResolver,
  UpdateAccountResolver,
  DeleteAccountResolver,
  UpsertAccountResolver,
  FindManyTypeformApplicationResolver,
  CreateTypeformApplicationResolver,
  UpdateTypeformApplicationResolver,
  DeleteTypeformApplicationResolver,
  CreateEventResolver,
  UpdateEventResolver,
  DeleteEventResolver,
  UpsertEventResolver,
  FindManyEventResolver,
  CreateProfileResolver,
  UpdateProfileResolver,
  // DeleteProfileResolver,
  UpsertProfileResolver,
  FindManyProfileResolver,
  FindUniqueProfileResolver,
  CreateEventReservationResolver,
  UpdateEventReservationResolver,
  DeleteEventReservationResolver,
  UpsertEventReservationResolver,
  FindManyEventReservationResolver,
  CreateVanityLinkResolver,
  UpdateVanityLinkResolver,
  DeleteVanityLinkResolver,
  FindManyVanityLinkResolver,
} from '@generated/type-graphql';

export const exposedResolvers: NonEmptyArray<Function> = [
  CreateAccountResolver,
  UpdateAccountResolver,
  DeleteAccountResolver,
  UpsertAccountResolver,
  FindManyTypeformApplicationResolver,
  CreateTypeformApplicationResolver,
  UpdateTypeformApplicationResolver,
  DeleteTypeformApplicationResolver,
  CreateEventResolver,
  UpdateEventResolver,
  DeleteEventResolver,
  UpsertEventResolver,
  FindManyEventResolver,
  CreateProfileResolver,
  UpdateProfileResolver,
  // DeleteProfileResolver,
  UpsertProfileResolver,
  FindManyProfileResolver,
  FindUniqueProfileResolver,
  CreateEventReservationResolver,
  UpdateEventReservationResolver,
  DeleteEventReservationResolver,
  UpsertEventReservationResolver,
  FindManyEventReservationResolver,
  CreateVanityLinkResolver,
  UpdateVanityLinkResolver,
  DeleteVanityLinkResolver,
  FindManyVanityLinkResolver,
];
